---
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, cache=FALSE, warning=FALSE)
source(here::here("script/setup.R"))
```

Analyzing product reviews is essential as it gives insights on how people feel, think, and react to a certain product. For this project, we will be analyzing reviews of two main products, Apple and Samsung phones, each of which has different models. The main purpose of this project is to analyze and compare the interaction of the consumers on Amazon's website with each of the models of those two phone brands, and how they describe them.

We will be studying the interaction by analyzing the difference in review texts between these two brands by consumers over time and distinguishing similarities as well as differences in the vocabulary used to describe the phone from all perspectives such as functionality, memory, state, etc. To get a better overview and more relevant results with respect to the technology used and the development of mobile phones, we will be focusing only on the newest three generations for each brand; Apple and Samsung phones that have been introduced in the years 2019, 2020, and 2021. The following are the models that this project will focus on:

* **Apple:**
  - iPhone 11 Pro Max
  - iPhone 11 Pro
  - iPhone 11
  - iPhone 12 Pro Max
  - iPhone 12 Pro
  - iPhone 12
  - iPhone 12 mini
  - iPhone 13 Pro Max
  - iPhone 13 Pro
  - iPhone 13
  - iPhone 13 mini

* **Samsung:**
  - Samsung Galaxy S20 FE
  - Samsung Galaxy S20 Plus
  - Samsung Galaxy Note 20 Ultra
  - Samsung Galaxy S21 FE
  - Samsung Galaxy S21 Plus
  - Samsung Galaxy 21 Ultra
  - Samsung Galaxy S22
  - Samsung Galaxy S22 Plus
  - Samsung Galaxy 22 Ultra

We will start by describing the data that is scraped from Amazon and the procedures taken to treat, clean, and prepare the data to transform it into a corpus with some graphical analysis. Further, we will perform a sentiment analysis to understand how consumers feel and react to these brands generally and models specifically. Then we will use unsupervised learning techniques, such as Latent Semantic Analysis (LSA) and Latent Dirichlet Allocation (LDA), to identify clusters and similarities in the reviews and to analyze topic attribution based on the model being reviewed. Finally, we will use supervised learning techniques, such as Random Forest, to predict future values such as sentiment prediction based on the brand. All the above will be used to conclude the consumers reactions to each of the brands and their models. 
